# Generate an array of zeroes using inbuilt numpy function.

In [1]:
# Python Program illustrating
# numpy.zeros method
  
import numpy as np
  
# manipulation with data-types
b = np.zeros((2,3), dtype= int )
print(b)

[[0 0 0]
 [0 0 0]]


# 2) Run the given code and find the dot product of both arrays.¶

In [2]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[9 2 3 2]
 [6 8 2 4]
 [4 5 2 6]]
[[5 3 5]
 [9 9 2]
 [9 5 9]
 [7 8 5]]


In [3]:
a.dot(b)

array([[104,  76,  86],
       [148, 132,  84],
       [125, 115,  78]])

## 3)Read the csv file provided using pandas and display the first 5 entries

In [4]:
import pandas as pd
data = pd.read_csv('data.csv')
data.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

## 4)Describe the data with all features.

In [5]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

## 5)Find the total count of missing values for each feature.

In [6]:
data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [7]:
data.isna().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

## 6)Display all the unique values from the 'DESCRIPTION’ column.

In [20]:
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

## 7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.


In [9]:
data.groupby('DESCRIPTION').mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

## 8)Generate a random sample of 10 rows from the data.

In [11]:
data.sample(n=10,replace=True)

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0         21                   Fort Stevenson State Park  ...   0.000284   0.135641
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
14        33                     Turtle River State Park  ...   0.000378   0.145220
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
2         23             Fort Abraham Lincoln State Park  ...   0.000399   0.119868
11        32                      Sully Creek State Park  ...   0.000030   0.024016
1         22                      Beaver Lake State Park  ...   0.000129   0.080067
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
6         27                   Lake Metigoshe State Park  ...   0.000751   0.212196

[10 rows x 6 columns]

## 9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

In [13]:
df = pd.DataFrame(data)


df = df.assign(New_feature = np.random.random())

print(df)

    OBJECTID  ... New_feature
0         21  ...    0.577312
1         22  ...    0.577312
2         23  ...    0.577312
3         24  ...    0.577312
4         25  ...    0.577312
5         26  ...    0.577312
6         27  ...    0.577312
7         28  ...    0.577312
8         29  ...    0.577312
9         30  ...    0.577312
10        31  ...    0.577312
11        32  ...    0.577312
12        35  ...    0.577312
13        36  ...    0.577312
14        33  ...    0.577312
15        34  ...    0.577312
16        37  ...    0.577312
17        38  ...    0.577312
18        39  ...    0.577312
19        40  ...    0.577312
20        41  ...    0.577312
21        43  ...    0.577312
22        44  ...    0.577312
23        45  ...    0.577312
24        42  ...    0.577312

[25 rows x 7 columns]


In [14]:
df.head()

OBJECTID                        UNIT_NAME  ... SHAPE.LEN  New_feature
0        21        Fort Stevenson State Park  ...  0.135641     0.577312
1        22           Beaver Lake State Park  ...  0.080067     0.577312
2        23  Fort Abraham Lincoln State Park  ...  0.119868     0.577312
3        24           Fort Ransom State Park  ...  0.128733     0.577312
4        25        Grahams Island State Park  ...  0.125546     0.577312

[5 rows x 7 columns]

## 10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [15]:
df=df.mask(df==0).fillna(df.mean())
#https://stackoverflow.com/questions/55319655/pandas-how-to-replace-zero-values-in-a-column-with-the-mean-of-that-column-for

In [16]:
df.head()

OBJECTID                        UNIT_NAME  ... SHAPE.LEN  New_feature
0        21        Fort Stevenson State Park  ...  0.135641     0.577312
1        22           Beaver Lake State Park  ...  0.080067     0.577312
2        23  Fort Abraham Lincoln State Park  ...  0.119868     0.577312
3        24           Fort Ransom State Park  ...  0.128733     0.577312
4        25        Grahams Island State Park  ...  0.125546     0.577312

[5 rows x 7 columns]

In [17]:
print(df['OBJECTID'].mean())    

33.0


In [18]:
df['OBJECTID'] = df['OBJECTID'].replace(33,0)  

In [19]:
df.OBJECTID

0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14     0
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64